services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicine-server
    ports:
      - "8787:8787"
    env_file:
      - ./backend/.env

    depends_on:
      - airtable-mock
    restart: on-failure

  airtable-mock:
    image: wiremock/wiremock:2.35.0
    container_name: mock-airtable
    ports:
      - "8089:8080"
    volumes:
      - ./mock/airtable:/home/wiremock
    command: --global-response-templating
