name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🛠️ Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: 🔍 Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: ✅ Run unit tests
        run: go test ./...

      - name: 🧱 Build binary
        run: go build ./...

      - name: 🧹 Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
          | sh -s -- -b ./bin v1.64.8

      - name: 🧹 Run golangci-lint
        run: ./bin/golangci-lint run
